name: CUGOS
description: Cascadia Users of GeoSpatial Open Source
author: Aaron Racicot
baseurl:
url: http://cugos.org/
future: true
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year-:month-:day/
